steps:

# Trigger unit tests for the backend.
- id: backend_unit_tests
  name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'test']
  dir: "backend"

# Trigger coverage tests for the backend.
- id: backend_coverage_report
  name: 'gcr.io/cloud-builders/mvn'
  args: ['jacoco:report']
  dir: "backend"

# Upload generated coverage tests data.
- id: upload_coverage_data
  name: gcr.io/cloud-builders/git
  entrypoint: bash
  args: ['./yaml_cloudbuild/codecov.sh']
  env:
  - 'CODECOV_TOKEN=${_CODECOV_TOKEN}'