runtime: nodejs10

manual_scaling:
  instances: 1

handlers:
- url: /.*?
  static_files: frontend/rolecall/dist/rolecall/index.html
  upload: frontend/rolecall/dist/rolecall/index.html
- url: /.*?
  static_dir:  frontend/rolecall/dist/rolecall
